.TH DEVICESINLAN 1 2017-02-07
.SH NAME
devicesinlan \- Scans all devices in your LAN. Then you can set an alias to your known devices in order to detect future strange devices in your net.

.SH SYNOPSIS
.TP
.B devicesinlan [ \fB\-\-wizard\fR | \fB\-\-interface\fR | \fB\-\-add\fR | \fB\-\-remove\fR | \fB\-\-list\fR ]

.SH DESCRIPTION GUI MODE
If you launch devicesinlan without parameters and you are in a graphic system (Linux or Windows) it launches the program with a Qt Interface.

In the app menu you have the followings features:

.TP
.B Devices > New Scan

.TP
.B Devices > Show devices database

.TP
.B Devices > Reset database

This option erases all known devices in database. 

.TP
.B Configuracion > Settings

In this dialog you can select your prefered language and you can configure the number of concurrence request.

.TP
.B Help > Help

.TP
.B Help > About

.TP
.B Help > Exit


.SH DESCRIPTION CONSOLE MODE
If you launch deviceslan with some parameters, it will be executed in console mode.

.TP
.B \-\-wizard. 
It list all interfaces in the system and lets you to select the one you wish and the number of concurrent request. After that, it scans the net and prints a list of the detected devices.

.TP
.B \-\-interface
Scans the net of the interface parameter and prints a list of the detected devices.

If a device is not known, it will be showed in red. Devices in green are trusted devices.

.TP
.B \-\-add

.TP
.B \-\-remove

.TP
.B \-\-list

