.TH DEVICESINLAN_GUI 1 2018\-11\-26
.SH NAME

.B devicesinlan_gui:
Busca todos los dispositivos de tu LAN. Despu\('es, puedes establecer alias a tus dispositivos conocidos para detectar dispositivos extra\(~nos en tu red.
.SH SYNOPSIS

devicesinlan_gui [\-\-help] [\-\-version] [\-\-debug DEBUG]
.SH DESCRIPCI\('ON

.PP
En el men\('u de la aplicaci\('on tienes las siguientes funcionalidades:
.PP
.RS
.B Dispositivo > Nuevo escaneado
.RE
.PP
.RS
.RS
Searches all devices in tha LAN and show them in a new tab. If some device is not in the known devices list it will be shown with a red background. Devices with a green background are trusted devices
.RE
.RE
.PP
.RS
.B Dispositivos > Muestra la base de datos de dispositivos
.RE
.PP
.RS
.RS
Muestra todo los dispositivos conocidos en una nueva pesta\(~na.
.RE
.RE
.PP
.RS
.RS
Hacer click derecho te permite editar la base de datos de dispositivos conocidos.
.RE
.RE
.PP
.RS
.B Dispositivos > Carga una lista de dispositivos
.RE
.PP
.RS
.RS
Carga una lista de dispositivos conocidos en formato xml.
.RE
.RE
.PP
.RS
.B Dispositivos > Grabar lista de dispositivos
.RE
.PP
.RS
.RS
Graba la lista de dispositivos conocidos a un fichero xml.
.RE
.RE
.PP
.RS
.B Dispositivos > Borrar la base de datos
.RE
.PP
.RS
.RS
Borra todos los dispositivos conocidos.
.RE
.RE
.PP
.RS
.RS
Esta opci\('on borra todos los dispositivos conocidos de la base de datos.
.RE
.RE
.PP
.RS
.B Configuraci\('on > Preferencias
.RE
.PP
.RS
.RS
In this dialog you can select your prefered language and you can configure the number of concurrence request.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.RS
Muestra esta informaci\('on de ayuda.
.RE
.RE
.PP
.RS
.B Ayuda > Acerca de
.RE
.PP
.RS
.RS
Shows information about DevicesInLAN license and authors.
.RE
.RE
.PP
.RS
.B Ayuda > Busca actualizaciones
.RE
.PP
.RS
.RS
Checks for updates in DevicesInLan repository.
.RE
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.PP
.RS
.RS
Sale del programa.
.RE
.RE
