.TH DEVICESINLAN_GUI 1 2018\-11\-19
.SH NAME

.B devicesinlan_gui:
Scans all devices in your LAN. Then you can set an alias to your known devices in order to detect future strange devices in your net.
.SH SYNOPSIS

devicesinlan_gui [\-\-help] [\-\-version] [\-\-debug DEBUG]
.SH DESCRIPCI\('ON

.PP
En el men\('u de la aplicaci\('on tienes las siguientes funcionalidades:
.PP
.RS
.B Dispositivo > Nuevo escaneado
.RE
.PP
.RS
.RS
Searches all devices in tha LAN and show them in a new tab. If some device is not in the known devices list it will be shown with a red background. Devices with a green background are trusted devices
.RE
.RE
.PP
.RS
.B Dispositivos > Muestra la base de datos de dispositivos
.RE
.PP
.RS
.RS
Muestra todo los dispositivos conocidos en una nueva pesta\(~na.
.RE
.RE
.PP
.RS
.RS
Hacer click derecho te permite editar la base de datos de dispositivos conocidos.
.RE
.RE
.PP
.RS
.B Dispositivos > Carga una lista de dispositivos
.RE
.PP
.RS
.RS
Carga una lista de dispositivos conocidos en formato xml.
.RE
.RE
.PP
.RS
.B Devices > Save devices list
.RE
.PP
.RS
.RS
Saves the known devices list to a xml file.
.RE
.RE
.PP
.RS
.B Devices > Reset database
.RE
.PP
.RS
.RS
Removes all known devices.
.RE
.RE
.PP
.RS
.RS
This option erases all known devices in database.
.RE
.RE
.PP
.RS
.B Configuration > Settings
.RE
.PP
.RS
.RS
In this dialog you can select your prefered language and you can configure the number of concurrence request.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.RS
Muestra esta informaci\('on de ayuda.
.RE
.RE
.PP
.RS
.B Help > About
.RE
.PP
.RS
.RS
Shows information about DevicesInLAN license and authors.
.RE
.RE
.PP
.RS
.B Help > Check for updates
.RE
.PP
.RS
.RS
Checks for updates in DevicesInLan repository.
.RE
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.PP
.RS
.RS
Exits from program.
.RE
.RE
