.TH DEVICESINLAN 1 2026\-09\-22
.SH NAME

.B devicesinlan:
Сканирует все устройства в локальной сети (LAN). Вы можете задать псевдонимы известным устройствам для обнаружения посторонних устройств.
.SH SYNOPSIS

devicesinlan [\-h] [\-\-version] [\-\-method {PingArp,ScapyArping,Scapy}] [\-\-interface INTERFACE | \-\-add | \-\-remove | \-\-list | \-\-load LOAD | \-\-save SAVE | \-\-reset] [\-\-debug DEBUG]
.SH ОПИСАНИЕ

.PP
Если запустить DevicesInLan без параметров, запустится мастер консоли.
.PP
Также можно использовать один из следующих параметров.
.PP
.B \-\-interface
.PP
.RS
Сканирует сеть выбранного интерфейса и выводит список обнаруженных устройств.
.RE
.PP
.RS
Неизвестные устройства отображаются красным цветом. Зеленым отмечены доверенные устройства.
.RE
.PP
.B \-\-add
.PP
.RS
Позволяет добавить известное устройство через консоль.
.RE
.PP
.B \-\-remove
.PP
.RS
Позволяет удалить известное устройство через консоль.
.RE
.PP
.B \-\-list
.PP
.RS
Отображает все известные устройства из базы данных в консоли.
.RE
.PP
.B \-\-load
.PP
.RS
Загружает список известных устройств в формате XML.
.RE
.PP
.B \-\-save
.PP
.RS
Сохраняет список известных устройств в XML\-файл.
.RE
.PP
.B \-\-debug
.PP
.RS
Выводит отладочную информацию при работе DevicesInLAN. По умолчанию отключено
.RE
.PP
.RS
Параметр может принимать значения: CRITICAL, ERROR, WARNING, INFO, DEBUG.
.RE
.PP
.B \-\-reset
.PP
.RS
Удаляет все известные устройства.
.RE
.SH МЕТОДЫ СКАНИРОВАНИЯ

.PP
DevicesInLan поддерживает несколько методов сканирования. Добавьте \-\-method в режиме консоли.
.PP
.B PingArp
.PP
.RS
Пытается установить сокет\-соединение с каждым устройством в LAN, затем получает MAC с помощью команды 'arp'
.RE
.PP
.RS
Метод PingArp используется по умолчанию в Windows и Linux.
.RE
.PP
.B Scapy
.PP
.RS
Использует Scapy для отправки ARP\-запросов и получения MAC\-адресов каждого IP в подсети.
.RE
.PP
.RS
Этот метод доступен в Windows и Linux, но требует прав администратора.
.RE
.PP
.RS
Кроме того, в Windows необходимо установить 'npcap'.
.RE
.PP
.B ScapyArping
.PP
.RS
Использует функцию arping из Scapy для отправки ARP\-запросов и получения информации о MAC\-адресах.
.RE
.PP
.RS
Этот метод доступен в Windows и Linux, но требует прав администратора.
.RE
.PP
.RS
Кроме того, в Windows необходимо установить 'npcap'.
.RE
.SH ПРИМЕРЫ

.PP
.B devicesinlan
.PP
.RS
Команда по умолчанию. Использует метод PingArp.
.RE
.PP
.B devicesinlan \-\-method ScapyArping
.PP
.RS
Использует метод ScapyArping.
.RE
