.TH DEVICESINLAN_GUI 1 2026\-09\-22
.SH NAME

.B devicesinlan_gui:
Сканирует все устройства в локальной сети (LAN). Вы можете задать псевдонимы известным устройствам для обнаружения посторонних устройств.
.SH SYNOPSIS

devicesinlan_gui [\-\-help] [\-\-version] [\-\-debug DEBUG]
.SH ОПИСАНИЕ

.PP
В меню программы доступны следующие функции:
.PP
.RS
.B Устройства > Новое сканирование
.RE
.PP
.RS
.RS
Сканирует все устройства в LAN и отображает их на новой вкладке. Неизвестные устройства подсвечиваются красным, доверенные — зеленым
.RE
.RE
.PP
.RS
.B Устройства > Показать базу устройств
.RE
.PP
.RS
.RS
Показывает все известные устройства на новой вкладке.
.RE
.RE
.PP
.RS
.RS
Правый клик позволяет редактировать базу данных известных устройств.
.RE
.RE
.PP
.RS
.B Устройства > Загрузить список устройств
.RE
.PP
.RS
.RS
Загружает список известных устройств в формате XML.
.RE
.RE
.PP
.RS
.B Устройства > Сохранить список устройств
.RE
.PP
.RS
.RS
Сохраняет список известных устройств в XML\-файл.
.RE
.RE
.PP
.RS
.B Устройства > Сбросить базу данных
.RE
.PP
.RS
.RS
Удаляет все известные устройства.
.RE
.RE
.PP
.RS
.RS
Эта опция стирает все известные устройства из базы данных.
.RE
.RE
.PP
.RS
.B Настройка > Параметры
.RE
.PP
.RS
.RS
В этом окне можно выбрать язык интерфейса и настроить количество параллельных запросов.
.RE
.RE
.PP
.RS
.B Справка > Справка
.RE
.PP
.RS
.RS
Отображает справочную информацию.
.RE
.RE
.PP
.RS
.B Справка > О программе
.RE
.PP
.RS
.RS
Показывает сведения о лицензии и авторах DevicesInLAN.
.RE
.RE
.PP
.RS
.B Справка > Проверить обновления
.RE
.PP
.RS
.RS
Проверяет наличие обновлений в репозитории DevicesInLan.
.RE
.RE
.PP
.RS
.B Справка > Выход
.RE
.PP
.RS
.RS
Завершает работу программы.
.RE
.RE
