.TH DEVICESINLAN_GUI 1 2018\-09\-01
.SH NAME

.B devicesinlan_gui:
Escan\('ea todos los dispositivos en tu red. Luego permite establecer un alias a tus dispositivos conocidos para que se pueda detectar dispositivos estra\(~nos en tu red.
.SH SYNOPSIS

devicesinlan_gui [\-\-help] [\-\-version] [\-\-debug DEBUG]
.SH DESCRIPCI\('ON

.PP
En el men\('u del aplicaci\('on tienes las siguientes funcionalidades:
.PP
.RS
.B Dispositivos \-> Nuevo escaneado
.RE
.PP
.RS
.RS
Busca todos los dispositivos existentes en la red y los muestra en una nueva pesta\(~na. Si alg\('un dispositivo no est\('a en la lista de dispositivos conocidos, ser\('a mostrado con un fondo rojo. Los dispositivos con un fondo verde son dispositivos confiables
.RE
.RE
.PP
.RS
.B Dispositivos > Mostrar base de datos
.RE
.PP
.RS
.RS
Muestra todos los dispositivos conocidos en una nueva pesta\(~na.
.RE
.RE
.PP
.RS
.RS
Al hacer un click derecho, podr\('as editar la base de datos de dispositivos conocidos.
.RE
.RE
.PP
.RS
.B Dispositivos \-> Carga una lista de dispositivos
.RE
.PP
.RS
.RS
Carga una lista de dispositivos conocidos en formato XML.
.RE
.RE
.PP
.RS
.B Dispositivos \-> Guarda la lista de dispositivos
.RE
.PP
.RS
.RS
Guarda la lista de dispositivos conocidos a un fichero XML.
.RE
.RE
.PP
.RS
.B Dispositivos > Borrar base de datos
.RE
.PP
.RS
.RS
Borra todos los dispositivos conocidos.
.RE
.RE
.PP
.RS
.RS
Esta opci\('on borra todos los dispositivos conocidos de la base de datos.
.RE
.RE
.PP
.RS
.B Configuraci\('on > Preferencias
.RE
.PP
.RS
.RS
En este dialogo, puedes seleccionar tu idioma favorita y puedes configurar el n\('umero de peticiones concurrentes.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.RS
Muestra esta ayuda.
.RE
.RE
.PP
.RS
.B Ayuda > Acerca de
.RE
.PP
.RS
.RS
Muestra informaci\('on sobre la licencia y los autores de DevicesInLan.
.RE
.RE
.PP
.RS
.B Ayuda \-> Buscar actualizaciones
.RE
.PP
.RS
.RS
Busca actualizaci\('ones en el repositorio de DevicesInLan.
.RE
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.PP
.RS
.RS
Sale del programa.
.RE
.RE
