.TH DEVICESINLAN 1 2017\-02\-21
.SH NAME

.B devicesinlan:
Escan\('ea todos los dispositivos en tu red. Luego permite establecer un alias a tus dispositivos conocidos para que se pueda detectar dispositivos estra\(~nos en tu red.
.SH SYNOPSIS

devicesinlan [\-h] [\-\-version] [\-\-debug DEBUG] [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list | \-\-load | \-\-save | \-\-reset ]
.SH DESCRIPCI\('ON DEL MODO INTERFAZ GR\('AFICO

.PP
If you launch devicesinlan without parameters and you are in a graphic system (Linux or Windows) it launches the program with a Qt Interface.
.PP
In the app menu you have the followings features:
.PP
.RS
.B Dispositivos \-> Nuevo escaneado
.RE
.PP
.RS
.B Dispositivos > Mostrar base de datos
.RE
.PP
.RS
.RS
Shows all known devices in a new tab.
.RE
.RE
.PP
.RS
.RS
Right click allows you to edit known devices database.
.RE
.RE
.PP
.RS
.B Dispositivos \-> Carga una lista de dispositivos
.RE
.PP
.RS
.RS
Loads a list of known devices in xml format.
.RE
.RE
.PP
.RS
.B Dispositivos \-> Guarda la lista de dispositivos
.RE
.PP
.RS
.RS
Saves the known devices list to a xml file.
.RE
.RE
.PP
.RS
.B Dispositivos > Borrar base de datos
.RE
.PP
.RS
.RS
Removes all known devices.
.RE
.RE
.PP
.RS
.RS
Esta opci\('on borra todos los dispositivos conocidos de la base de datos.
.RE
.RE
.PP
.RS
.B Configuraci\('on > Preferencias
.RE
.PP
.RS
.RS
En este dialogo, puedes seleccionar tu idioma favorita y puedes configurar el n\('umero de peticiones concurrentes.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.RS
Muestra esta ayuda.
.RE
.RE
.PP
.RS
.B Ayuda > Acerca de
.RE
.PP
.RS
.RS
Muestra informaci\('on sobre la licencia y los autores de DevicesInLan.
.RE
.RE
.PP
.RS
.B Ayuda \-> Buscar actualizaciones
.RE
.PP
.RS
.RS
Checks for updates in DevicesInLan repository.
.RE
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.PP
.RS
.RS
Sale del programa.
.RE
.RE
.SH DESCRIPCI\('ON DEL MODO CONSOLA

.PP
If you launch deviceslan with [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list | \-\-load | \-\-save | \-\-reset ], it will be executed in console mode.
.PP
.RS
.B \-\-wizard
.RE
.PP
.RS
.RS
Lista todos los interfaces de red en el sistema y te permite seleccionar uno y establecer el n\('umero de peticiones concurrente. Despu\('es de eso, escan\('ea la red y visualiza una lista de los dispositivos detectados.
.RE
.RE
.PP
.RS
.B \-\-interface
.RE
.PP
.RS
.RS
Scans the net of the interface parameter and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.RS
If a device is not known, it will be showed in red. Devices in green are trusted devices.
.RE
.RE
.PP
.RS
.B \-\-add
.RE
.PP
.RS
.RS
Permite a\(~nadir un dispositivo conocido desde consola.
.RE
.RE
.PP
.RS
.B \-\-remove
.RE
.PP
.RS
.RS
Permite borrar un dispositivo conocido desde consola.
.RE
.RE
.PP
.RS
.B \-\-list
.RE
.PP
.RS
.RS
Shows all known devices in database from console.
.RE
.RE
.PP
.RS
.B \-\-load
.RE
.PP
.RS
.RS
Loads a list of known devices in xml format.
.RE
.RE
.PP
.RS
.B \-\-save
.RE
.PP
.RS
.RS
Saves the known devices list to a xml file.
.RE
.RE
.PP
.RS
.B \-\-reset
.RE
.PP
.RS
.RS
Removes all known devices.
.RE
.RE
