.TH DEVICESINLAN 1 2017\-02\-07
.SH NAME
.B devicesinlan:
Escanéa todos los dispositivos en tu red. Luego permite establecer un alias a tus dispositivos conocidos para que se pueda detectar dispositivos estraños en tu red.
.SH SYNOPSIS
devicesinlan [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list ]
.SH DESCRIPCIÓN DEL MODO INTERFAZ GRÁFICO
.PP
If you launch devicesinlan without parameters and you are in a graphic system (Linux or Windows) it launches the program with a Qt Interface.
.PP
In the app menu you have the followings features:
.PP
.RS
.B Devices > New Scan
.RE
.PP
.RS
.B Devices > Show devices database
.RE
.PP
.RS
.B Dispositivos > Borrar base de datos
.RE
.PP
.RS
.RS
Esta opción borra todos los dispositivos conocidos de la base de datos.
.RE
.RE
.PP
.RS
.B Configuración > Preferencias
.RE
.PP
.RS
.RS
En este dialogo, puedes seleccionar tu idioma favorita y puedes configurar el número de peticiones concurrentes.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.B Ayuda > Acerca de
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.SH DESCRIPCIÓN DEL MODO CONSOLA
.PP
If you launch deviceslan with some parameters, it will be executed in console mode.
.PP
.RS
.B \-\-wizard
.RE
.PP
.RS
.RS
It list all interfaces in the system and lets you to select the one you wish and the number of concurrent request. After that, it scans the net and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.B \-\-interface
.RE
.PP
.RS
.RS
Scans the net of the interface parameter and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.RS
If a device is not known, it will be showed in red. Devices in green are trusted devices.
.RE
.RE
.PP
.RS
.B \-\-add
.RE
.PP
.RS
.B \-\-remove
.RE
.PP
.RS
.B \-\-list
.RE
