.TH DEVICESINLAN 1 2017\-02\-26
.SH NAME

.B devicesinlan:
Scans all devices in your LAN. Then you can set an alias to your known devices in order to detect future strange devices in your net.
.SH SYNOPSIS

devicesinlan [\-h] [\-\-version] [\-\-debug DEBUG] [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list | \-\-load | \-\-save | \-\-reset ]
.SH GUI MODE DESCRIPTION

.PP
If you launch devicesinlan without parameters and you are in a graphic system (Linux or Windows) it launches the program with a Qt Interface.
.PP
In the app menu you have the followings features:
.PP
.RS
.B Devices > New Scan
.RE
.PP
.RS
.B Devices > Show devices database
.RE
.PP
.RS
.RS
Shows all known devices in a new tab.
.RE
.RE
.PP
.RS
.RS
Right click allows you to edit known devices database.
.RE
.RE
.PP
.RS
.B Devices > Load devices list
.RE
.PP
.RS
.RS
Loads a list of known devices in xml format.
.RE
.RE
.PP
.RS
.B Devices > Save devices list
.RE
.PP
.RS
.RS
Saves the known devices list to a xml file.
.RE
.RE
.PP
.RS
.B Devices > Reset database
.RE
.PP
.RS
.RS
Removes all known devices.
.RE
.RE
.PP
.RS
.RS
This option erases all known devices in database.
.RE
.RE
.PP
.RS
.B Configuration > Settings
.RE
.PP
.RS
.RS
In this dialog you can select your prefered language and you can configure the number of concurrence request.
.RE
.RE
.PP
.RS
.B Help > Help
.RE
.PP
.RS
.RS
Shows this help information.
.RE
.RE
.PP
.RS
.B Help > About
.RE
.PP
.RS
.RS
Shows information about DevicesInLAN license and authors.
.RE
.RE
.PP
.RS
.B Help > Check for updates
.RE
.PP
.RS
.RS
Checks for updates in DevicesInLan repository.
.RE
.RE
.PP
.RS
.B Help > Exit
.RE
.PP
.RS
.RS
Exits from program.
.RE
.RE
.SH CONSOLE MODE DESCRIPTION

.PP
If you launch deviceslan with [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list | \-\-load | \-\-save | \-\-reset ], it will be executed in console mode.
.PP
.RS
.B \-\-wizard
.RE
.PP
.RS
.RS
It list all interfaces in the system and lets you to select the one you wish and the number of concurrent request. After that, it scans the net and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.B \-\-interface
.RE
.PP
.RS
.RS
Scans the net of the interface parameter and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.RS
If a device is not known, it will be showed in red. Devices in green are trusted devices.
.RE
.RE
.PP
.RS
.B \-\-add
.RE
.PP
.RS
.RS
Allows to add a known device from console.
.RE
.RE
.PP
.RS
.B \-\-remove
.RE
.PP
.RS
.RS
Allows to remove a known device from console.
.RE
.RE
.PP
.RS
.B \-\-list
.RE
.PP
.RS
.RS
Shows all known devices in database from console.
.RE
.RE
.PP
.RS
.B \-\-load
.RE
.PP
.RS
.RS
Loads a list of known devices in xml format.
.RE
.RE
.PP
.RS
.B \-\-save
.RE
.PP
.RS
.RS
Saves the known devices list to a xml file.
.RE
.RE
.PP
.RS
.B \-\-debug
.RE
.PP
.RS
.RS
Gives debugging information when running DevicesInLAN. It's deactivated by default
.RE
.RE
.PP
.RS
.RS
The parameter can take this options: CRITICAL, ERROR, WARNING, INFO, DEBUG.
.RE
.RE
.PP
.RS
.B \-\-reset
.RE
.PP
.RS
.RS
Removes all known devices.
.RE
.RE
