.TH DEVICESINLAN 1 2017\-02\-08
.SH NAME

.B devicesinlan:
Escan\('ea todos los dispositivos en tu red. Luego permite establecer un alias a tus dispositivos conocidos para que se pueda detectar dispositivos estra\(~nos en tu red.
.SH SYNOPSIS

devicesinlan [ \-\-wizard | \-\-interface | \-\-add | \-\-remove | \-\-list ]
.SH DESCRIPCI\('ON DEL MODO INTERFAZ GR\('AFICO

.PP
If you launch devicesinlan without parameters and you are in a graphic system (Linux or Windows) it launches the program with a Qt Interface.
.PP
In the app menu you have the followings features:
.PP
.RS
.B Dispositivos \-> Nuevo escaneado
.RE
.PP
.RS
.B Dispositivos > Mostrar base de datos
.RE
.PP
.RS
.B Dispositivos > Borrar base de datos
.RE
.PP
.RS
.RS
Esta opci\('on borra todos los dispositivos conocidos de la base de datos.
.RE
.RE
.PP
.RS
.B Configuraci\('on > Preferencias
.RE
.PP
.RS
.RS
En este dialogo, puedes seleccionar tu idioma favorita y puedes configurar el n\('umero de peticiones concurrentes.
.RE
.RE
.PP
.RS
.B Ayuda > Ayuda
.RE
.PP
.RS
.B Ayuda > Acerca de
.RE
.PP
.RS
.B Ayuda > Salir
.RE
.SH DESCRIPCI\('ON DEL MODO CONSOLA

.PP
If you launch deviceslan with some parameters, it will be executed in console mode.
.PP
.RS
.B \-\-wizard
.RE
.PP
.RS
.RS
It list all interfaces in the system and lets you to select the one you wish and the number of concurrent request. After that, it scans the net and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.B \-\-interface
.RE
.PP
.RS
.RS
Scans the net of the interface parameter and prints a list of the detected devices.
.RE
.RE
.PP
.RS
.RS
If a device is not known, it will be showed in red. Devices in green are trusted devices.
.RE
.RE
.PP
.RS
.B \-\-add
.RE
.PP
.RS
.B \-\-remove
.RE
.PP
.RS
.B \-\-list
.RE
