.TH DEVICESINLAN_GUI 1 2026\-09\-22
.SH NAME

.B devicesinlan_gui:
Scanează toate dispozitivele din LAN. Apoi puteți seta un alias dispozitivelor cunoscute pentru a detecta dispozitive străine pe rețea.
.SH SYNOPSIS

devicesinlan_gui [\-\-help] [\-\-version] [\-\-debug DEBUG]
.SH DESCRIERE

.PP
În meniul aplicației aveți următoarele funcționalități:
.PP
.RS
.B Dispozitive > Scanare nouă
.RE
.PP
.RS
.RS
Caută toate dispozitivele din LAN și le afișează într\-o filă nouă. Dacă un dispozitiv nu este în lista dispozitivelor cunoscute, va fi afișat cu fundal roșu. Dispozitivele cu fundal verde sunt de încredere
.RE
.RE
.PP
.RS
.B Dispozitive > Arată baza de date a dispozitivelor
.RE
.PP
.RS
.RS
Afișează toate dispozitivele cunoscute într\-o filă nouă.
.RE
.RE
.PP
.RS
.RS
Clic dreapta vă permite să editați baza de date a dispozitivelor cunoscute.
.RE
.RE
.PP
.RS
.B Dispozitive > Încarcă lista dispozitivelor
.RE
.PP
.RS
.RS
Încarcă o listă de dispozitive cunoscute în format XML.
.RE
.RE
.PP
.RS
.B Dispozitive > Salvează lista dispozitivelor
.RE
.PP
.RS
.RS
Salvează lista de dispozitive cunoscute într\-un fișier XML.
.RE
.RE
.PP
.RS
.B Dispozitive > Resetează baza de date
.RE
.PP
.RS
.RS
Elimină toate dispozitivele cunoscute.
.RE
.RE
.PP
.RS
.RS
Această opțiune șterge toate dispozitivele cunoscute din baza de date.
.RE
.RE
.PP
.RS
.B Configurare > Setări
.RE
.PP
.RS
.RS
În această fereastră puteți selecta limba preferată și configura numărul de cereri concurente.
.RE
.RE
.PP
.RS
.B Ajutor > Ajutor
.RE
.PP
.RS
.RS
Afișează aceste informații de ajutor.
.RE
.RE
.PP
.RS
.B Ajutor > Despre
.RE
.PP
.RS
.RS
Afișează informații despre licența și autorii DevicesInLAN.
.RE
.RE
.PP
.RS
.B Ajutor > Verifică actualizări
.RE
.PP
.RS
.RS
Verifică actualizări în depozitul DevicesInLan.
.RE
.RE
.PP
.RS
.B Ajutor > Ieșire
.RE
.PP
.RS
.RS
Iese din program.
.RE
.RE
