.TH DEVICESINLAN 1 2026\-09\-22
.SH NAME

.B devicesinlan:
Scanează toate dispozitivele din LAN. Apoi puteți seta un alias dispozitivelor cunoscute pentru a detecta dispozitive străine pe rețea.
.SH SYNOPSIS

devicesinlan [\-h] [\-\-version] [\-\-method {PingArp,ScapyArping,Scapy}] [\-\-interface INTERFACE | \-\-add | \-\-remove | \-\-list | \-\-load LOAD | \-\-save SAVE | \-\-reset] [\-\-debug DEBUG]
.SH DESCRIERE

.PP
Dacă lansați DevicesInLan fără parametri, este pornit un asistent în consolă.
.PP
De asemenea, puteți utiliza unul dintre acești parametri.
.PP
.B \-\-interface
.PP
.RS
Scanează rețeaua interfeței parametru și afișează o listă a dispozitivelor detectate.
.RE
.PP
.RS
Dacă un dispozitiv nu este cunoscut, va fi afișat în roșu. Dispozitivele în verde sunt de încredere.
.RE
.PP
.B \-\-add
.PP
.RS
Permite adăugarea unui dispozitiv cunoscut din consolă.
.RE
.PP
.B \-\-remove
.PP
.RS
Permite eliminarea unui dispozitiv cunoscut din consolă.
.RE
.PP
.B \-\-list
.PP
.RS
Afișează toate dispozitivele cunoscute din baza de date în consolă.
.RE
.PP
.B \-\-load
.PP
.RS
Încarcă o listă de dispozitive cunoscute în format XML.
.RE
.PP
.B \-\-save
.PP
.RS
Salvează lista de dispozitive cunoscute într\-un fișier XML.
.RE
.PP
.B \-\-debug
.PP
.RS
Oferă informații de depanare la rularea DevicesInLAN. Este dezactivat implicit
.RE
.PP
.RS
Parametrul poate lua următoarele opțiuni: CRITICAL, ERROR, WARNING, INFO, DEBUG.
.RE
.PP
.B \-\-reset
.PP
.RS
Elimină toate dispozitivele cunoscute.
.RE
.SH METODE DE SCANARE

.PP
DevicesInLan poate folosi mai multe metode pentru a scana dispozitive. Trebuie doar să adăugați \-\-method în modul consolă.
.PP
.B PingArp
.PP
.RS
Încearcă să stabilească o conexiune socket cu orice dispozitiv din LAN. Apoi caută informațiile MAC cu comanda 'arp'
.RE
.PP
.RS
Metoda PingArp este utilizată implicit pe versiunile Windows și Linux.
.RE
.PP
.B Scapy
.PP
.RS
Utilizează Scapy pentru a crea o cerere ARP și a captura răspunsul pentru fiecare IP din subrețea pentru a obține informațiile MAC.
.RE
.PP
.RS
Această metodă poate fi utilizată pe Windows și Linux, dar trebuie executată cu drepturi de administrator.
.RE
.PP
.RS
În plus, trebuie să instalați 'npcap' pentru a rula pe Windows.
.RE
.PP
.B ScapyArping
.PP
.RS
Utilizează funcția arping din Scapy pentru a crea cereri ARP și a captura răspunsurile pentru fiecare IP din subrețea.
.RE
.PP
.RS
Această metodă poate fi utilizată pe Windows și Linux, dar trebuie executată cu drepturi de administrator.
.RE
.PP
.RS
În plus, trebuie să instalați 'npcap' pentru a rula pe Windows.
.RE
.SH EXEMPLE

.PP
.B devicesinlan
.PP
.RS
Comandă implicită. Utilizează metoda PingArp.
.RE
.PP
.B devicesinlan \-\-method ScapyArping
.PP
.RS
Utilizează metoda ScapyArping.
.RE
